# Generated by Django 3.2.12 on 2023-05-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20230523_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='replie',
            old_name='reply_id',
            new_name='id',
        ),
    ]
