# Generated by Django 3.2.12 on 2023-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_auto_20230523_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='replie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
